### ISSUE TITLE
[BUG] Inconsistent validations about the ledger

### ISSUE THREAD

**Issue by dhythm** [BoostryJP/ibet-Prime#208]
**Describe the bug**
An empty footer could be registered as a ledger template.
However, the ledger history API (`GET /[domain}/[token_address}/history/{ledger_id}`) will be failed to get the ledger with empty footer after the registration.

**Expected behavior**
An error doesn't happen and data should be returned.

**Additional context**
It could be better for the validation,
- each header (ledger and details) doesn't allow empty input because there is the title / heading item on top of the header
- each footer (ledger and details) allows empty input because the footer is isolated item.

**Comment by YoshihitoAso** [comment]
Thank you for your feedback.

The different null constraints in the system are a bug and will be fixed.

Regarding your suggestion that the header should be non-null, this feature is built to be used for general purpose ledgers, so it is possible for a ledger to not have a header.
Therefore, we think it is right to design the header to allow null.

**Comment by dhythm** [comment]
Thank you for your reply and your idea is understood for me.
I will reconsider whether add the validation for the header at our frontend service or not.

Anyway, I'm waiting for fixing the bug. Thx 👍
