### ISSUE TITLE
[FEATURE] EOA password allows to input special characters

### ISSUE THREAD

**Issue by dhythm** [BoostryJP/ibet-Prime#209]
**Is your feature request related to a problem? Please describe.**
EOA password doesn't allow to input special characters at the moment.
On the other hand, RSA passphrase allows them.

It would be better to enable to input some special characters for EOA password as well.

**Describe the solution you'd like**
Allow special characters (like *+.\()?[]^$-|!#%&"',/:;<=>@_`{}~) for EOA password.

**Comment by YoshihitoAso** [comment]
The following regular expressions are allowed for passphrases, for EOA and personal information encryption keys (RSA keys) respectively.

```python
EOA_PASSWORD_PATTERN = \
    os.environ.get("EOA_PASSWORD_PATTERN") or \
    "^[a-zA-Z0-9]{8,20}$"
PERSONAL_INFO_RSA_PASSPHRASE_PATTERN = \
    os.environ.get("PERSONAL_INFO_RSA_PASSPHRASE_PATTERN") or \
    "^[a-zA-Z0-9 \*\+\.\\\(\)\?\[\]\^\$\-\|!#%&\"',/:;<=>@_`{}~]{8,}$"
```


The default settings are as above and can be controlled by environment variables.

We understood that the suggestion you gave us is to align all allowed characters in the passphrase, so we will check the feasibility first.
