### ISSUE TITLE
[Holders] Get balance list and balance for an account

### ISSUE THREAD

**Issue by dhythm** [BoostryJP/ibet-Prime#287]
## Is your feature request related to a problem? Please describe.
Holders api needs `token_address` at the moment.
So it needs to get all tokens (n) and get all holders (m) (= n * m requests) if we want to get balance for an account. 

## Describe the solution you'd like
To get balances of holding tokens for an account (an EOA).

## Describe alternatives you've considered
To call API with EOA of an account, then return all balances of holding tokens

## Additional context
nothing.

**Comment by urushibata-k** [comment]
URL: `GET: /position/{account_address}`
Header param:
- issuer-address: optional

Query param:
- token_type: optional
- offset: optional
- limit: optional

---
URL: `GET: /position/{account_address}/{token_address}`
Header param:
- issuer-address: required

**Comment by dhythm** [comment]
I would be awesome if the return value includes `token_name`, `token_address` and `balance` 🙏
