### ISSUE TITLE
[FEATURE] Add `personal_information` to transfer list API response

### ISSUE THREAD

**Issue by purplesmoke05** [BoostryJP/ibet-Prime#557]
## Is your feature request related to a problem? Please describe.

There are use cases where the personal information data of the token holder is to be referenced together with other contents.
It is efficient in terms of API calls to include the token holder's personal data in some API response.
In particular, personal information should be included in the response when referring to transfer history.

Ref: https://github.com/BoostryJP/ibet-Prime/issues/535

## Describe the solution you'd like

Add `personal_information` to transfer list API response

**Comment by ouchikai** [comment]
https://github.com/BoostryJP/E-Prime-Dashboard/issues/3738
こちらで対応します
